{"name": "test_verify_error_message_with_invalid_credentials", "status": "passed", "start": 1726248439508, "stop": 1726248444728, "uuid": "7854eac8-fa49-422c-a160-8f73d8d02d27", "historyId": "02d1f4d059022f8176ed810b654a99f3", "testCaseId": "02d1f4d059022f8176ed810b654a99f3", "fullName": "tests.test_login#test_verify_error_message_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Laptop-Diego"}, {"name": "thread", "value": "20112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}